// <auto-generated />
namespace ShopDiaryProject.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLocationIdToShopList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLocationIdToShopList));
        
        string IMigrationMetadata.Id
        {
            get { return "201811221747194_AddLocationIdToShopList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
